//
//  SongRow.swift
//  Ampwave
//
//  Reusable song row component with artwork, title, and artist.
//

internal import SwiftUI

/// The "E" marker Apple Music and Spotify use for explicit tracks.
struct ExplicitBadge: View {
  var size: CGFloat = 12

  var body: some View {
    Image(systemName: "e.square.fill")
      .font(.system(size: size))
      .foregroundStyle(.secondary)
      .accessibilityLabel("Explicit")
  }
}

/// Provenance marker for tracks generated by a recognized AI provider.
struct AIGeneratedBadge: View {
  var size: CGFloat = 12

  var body: some View {
    ZStack {
      RoundedRectangle(cornerRadius: size * 0.28, style: .continuous)
        .fill(
          LinearGradient(
            colors: [
              Color(red: 0.45, green: 0.32, blue: 0.95).opacity(0.20),
              Color(red: 0.16, green: 0.58, blue: 0.98).opacity(0.18),
            ],
            startPoint: .topLeading,
            endPoint: .bottomTrailing
          )
        )
        .overlay {
          RoundedRectangle(cornerRadius: size * 0.28, style: .continuous)
            .stroke(
              LinearGradient(
                colors: [
                  Color(red: 0.58, green: 0.45, blue: 1.0).opacity(0.62),
                  Color(red: 0.28, green: 0.72, blue: 1.0).opacity(0.62),
                ],
                startPoint: .topLeading,
                endPoint: .bottomTrailing
              ),
              lineWidth: max(0.6, size * 0.07)
            )
        }

      Image(systemName: "wand.and.stars")
        .font(.system(size: size * 0.62, weight: .semibold))
        .symbolRenderingMode(.hierarchical)
        .foregroundStyle(
          LinearGradient(
            colors: [
              Color(red: 0.52, green: 0.40, blue: 1.0),
              Color(red: 0.20, green: 0.68, blue: 1.0),
            ],
            startPoint: .topLeading,
            endPoint: .bottomTrailing
          )
        )
    }
    .frame(width: size * 1.32, height: size * 1.08)
    .fixedSize()
    .accessibilityLabel("AI generated by Suno")
  }
}

struct SongRow: View {
  let song: LibrarySong
  let isCurrent: Bool
  var showArtwork: Bool = true

  @State private var playback = PlaybackController.shared

  var body: some View {
    HStack(spacing: 12) {
      if showArtwork {
        ArtworkImage(artworkPath: song.effectiveArtworkPath, size: 50, cornerRadius: 6)
      }

      VStack(alignment: .leading, spacing: 3) {
        Text(song.title)
          .font(.system(size: 16, weight: isCurrent ? .semibold : .regular))
          .lineLimit(1)

        HStack(spacing: 4) {
          Text(song.artist)
            .font(.system(size: 14))
            .foregroundStyle(.secondary)
            .lineLimit(1)
            if song.isExplicit { ExplicitBadge(size: 12) }
            if song.isAIGenerated { AIGeneratedBadge(size: 12) }
        }
      }

      Spacer()

      if song.shouldSyncToWatch {
        Image(systemName: "applewatch")
          .font(.system(size: 12))
          .foregroundStyle(.secondary)
      }

      if isCurrent {
        AmpwaveEqualizerMark(isAnimated: playback.isPlaying)
          .frame(width: 22, height: 18)
          .accessibilityLabel(playback.isPlaying ? "Now playing" : "Current song, paused")
      }
    }
    .padding(.vertical, 4)
    .songContextMenu(song: song)
  }
}

// MARK: - Compact Song Row

struct CompactSongRow: View {
  let song: LibrarySong
  let isCurrent: Bool
  @State private var playback = PlaybackController.shared

  var body: some View {
    HStack(spacing: 12) {
      ArtworkImage(artworkPath: song.effectiveArtworkPath, size: 40, cornerRadius: 4)

      VStack(alignment: .leading, spacing: 2) {
        Text(song.title)
          .font(.system(size: 15, weight: isCurrent ? .semibold : .medium))
          .lineLimit(1)

        HStack(spacing: 4) {
          if song.isExplicit { ExplicitBadge(size: 11) }
          if song.isAIGenerated { AIGeneratedBadge(size: 11) }
          Text(song.artist)
            .font(.system(size: 13))
            .foregroundStyle(.secondary)
            .lineLimit(1)
        }
      }

      Spacer()

      if isCurrent {
        AmpwaveEqualizerMark(isAnimated: playback.isPlaying)
          .frame(width: 20, height: 15)
          .accessibilityLabel(playback.isPlaying ? "Now playing" : "Current song, paused")
      }
    }
    .padding(.vertical, 4)
    .songContextMenu(song: song)
  }
}

// MARK: - Song Row with Number

struct NumberedSongRow: View {
  let number: Int
  let song: LibrarySong
  let isCurrent: Bool
  @State private var playback = PlaybackController.shared

  var body: some View {
    HStack(spacing: 12) {
      // Number or playing indicator
      if isCurrent {
        AmpwaveEqualizerMark(isAnimated: playback.isPlaying)
          .frame(width: 22, height: 16)
          .frame(width: 28, alignment: .center)
          .accessibilityLabel(playback.isPlaying ? "Now playing" : "Current song, paused")
      } else {
        Text("\(number)")
          .font(.system(size: 14, weight: .medium))
          .foregroundStyle(.secondary)
          .frame(width: 28, alignment: .center)
      }

      ArtworkImage(artworkPath: song.effectiveArtworkPath, size: 40, cornerRadius: 4)

      VStack(alignment: .leading, spacing: 2) {
        Text(song.title)
          .font(.system(size: 15, weight: isCurrent ? .semibold : .regular))
          .lineLimit(1)

        HStack(spacing: 4) {
          if song.isExplicit { ExplicitBadge(size: 11) }
          if song.isAIGenerated { AIGeneratedBadge(size: 11) }
          Text(song.artist)
            .font(.system(size: 13))
            .foregroundStyle(.secondary)
            .lineLimit(1)
        }
      }

      Spacer()
    }
    .padding(.vertical, 4)
    .songContextMenu(song: song)
  }
}
