//
//  SongRow.swift
//  Ampwave
//
//  Reusable song row component with artwork, title, and artist.
//

internal import SwiftUI

/// The "E" marker Apple Music and Spotify use for explicit tracks.
struct ExplicitBadge: View {
  var size: CGFloat = 12

  var body: some View {
    Image(systemName: "e.square.fill")
      .font(.system(size: size))
      .foregroundStyle(.secondary)
      .accessibilityLabel("Explicit")
  }
}

/// Provenance marker for tracks generated by a recognized AI provider.
struct AIGeneratedBadge: View {
  var size: CGFloat = 12

  var body: some View {
    HStack(spacing: size * 0.22) {
      Image(systemName: "sparkles")
        .font(.system(size: size * 0.68, weight: .bold))
        .symbolRenderingMode(.hierarchical)

      Text("AI")
        .font(.system(size: size * 0.62, weight: .heavy, design: .rounded))
        .tracking(size * 0.015)
    }
    .foregroundStyle(
      LinearGradient(
        colors: [
          Color(red: 0.60, green: 0.45, blue: 1.0),
          Color(red: 0.18, green: 0.72, blue: 1.0),
        ],
        startPoint: .topLeading,
        endPoint: .bottomTrailing
      )
    )
    .padding(.horizontal, size * 0.40)
    .frame(height: size * 1.22)
    .background {
      Capsule(style: .continuous)
        .fill(
          LinearGradient(
            colors: [
              Color(red: 0.45, green: 0.28, blue: 0.95).opacity(0.20),
              Color(red: 0.10, green: 0.64, blue: 1.0).opacity(0.14),
            ],
            startPoint: .topLeading,
            endPoint: .bottomTrailing
          )
        )
    }
    .overlay {
      Capsule(style: .continuous)
        .stroke(
          LinearGradient(
            colors: [
              Color(red: 0.68, green: 0.54, blue: 1.0).opacity(0.72),
              Color(red: 0.22, green: 0.72, blue: 1.0).opacity(0.52),
            ],
            startPoint: .topLeading,
            endPoint: .bottomTrailing
          ),
          lineWidth: max(0.6, size * 0.065)
        )
    }
    .shadow(color: Color.purple.opacity(0.12), radius: size * 0.18, y: size * 0.08)
    .fixedSize()
    .accessibilityElement(children: .ignore)
    .accessibilityLabel("AI-generated or AI-assisted")
  }
}

struct RemoteSongBadge: View {
  let isDownloading: Bool
  var size: CGFloat = 11

  var body: some View {
    Image(systemName: isDownloading ? "arrow.down.circle" : "dot.radiowaves.left.and.right")
      .font(.system(size: size, weight: .semibold))
      .foregroundStyle(.secondary)
      .accessibilityLabel(isDownloading ? "Downloading" : "Streaming from media server")
  }
}

struct SongRow: View {
  let song: LibrarySong
  let isCurrent: Bool
  var showArtwork: Bool = true
  var artworkShape: LibraryArtworkShape = .roundedRectangle

  @State private var playback = PlaybackController.shared

  var body: some View {
    HStack(spacing: 12) {
      if showArtwork {
        ArtworkImage(
          artworkPath: song.effectiveArtworkPath,
          size: 50,
          cornerRadius: artworkShape == .circle ? 25 : 6
        )
      }

      VStack(alignment: .leading, spacing: 3) {
        Text(song.title)
          .font(.system(size: 16, weight: isCurrent ? .semibold : .regular))
          .lineLimit(1)

        HStack(spacing: 4) {
          Text(song.artist)
            .font(.system(size: 14))
            .foregroundStyle(.secondary)
            .lineLimit(1)
            if song.isExplicit { ExplicitBadge(size: 12) }
            if song.isAIGenerated { AIGeneratedBadge(size: 12) }
            if song.isRemote && !song.remoteIsDownloaded {
              RemoteSongBadge(isDownloading: song.remoteDownloadRequested, size: 11)
            }
        }
      }

      Spacer()

      if isCurrent {
        AmpwaveEqualizerMark(isAnimated: playback.isPlaying)
          .frame(width: 22, height: 18)
          .accessibilityLabel(playback.isPlaying ? "Now playing" : "Current song, paused")
      }
    }
    .padding(.vertical, 4)
    .songContextMenu(song: song)
  }
}

// MARK: - Compact Song Row

struct CompactSongRow: View {
  let song: LibrarySong
  let isCurrent: Bool
  @State private var playback = PlaybackController.shared

  var body: some View {
    HStack(spacing: 12) {
      ArtworkImage(artworkPath: song.effectiveArtworkPath, size: 40, cornerRadius: 4)

      VStack(alignment: .leading, spacing: 2) {
        Text(song.title)
          .font(.system(size: 15, weight: isCurrent ? .semibold : .medium))
          .lineLimit(1)

        HStack(spacing: 4) {
          if song.isExplicit { ExplicitBadge(size: 11) }
          if song.isAIGenerated { AIGeneratedBadge(size: 11) }
          if song.isRemote && !song.remoteIsDownloaded {
            RemoteSongBadge(isDownloading: song.remoteDownloadRequested, size: 10)
          }
          Text(song.artist)
            .font(.system(size: 13))
            .foregroundStyle(.secondary)
            .lineLimit(1)
        }
      }

      Spacer()

      if isCurrent {
        AmpwaveEqualizerMark(isAnimated: playback.isPlaying)
          .frame(width: 20, height: 15)
          .accessibilityLabel(playback.isPlaying ? "Now playing" : "Current song, paused")
      }
    }
    .padding(.vertical, 4)
    .songContextMenu(song: song)
  }
}

// MARK: - Song Row with Number

struct NumberedSongRow: View {
  let number: Int
  let song: LibrarySong
  let isCurrent: Bool
  var artworkShape: LibraryArtworkShape = .roundedRectangle
  @State private var playback = PlaybackController.shared

  var body: some View {
    HStack(spacing: 12) {
      // Number or playing indicator
      if isCurrent {
        AmpwaveEqualizerMark(isAnimated: playback.isPlaying)
          .frame(width: 22, height: 16)
          .frame(width: 28, alignment: .center)
          .accessibilityLabel(playback.isPlaying ? "Now playing" : "Current song, paused")
      } else {
        Text("\(number)")
          .font(.system(size: 14, weight: .medium))
          .foregroundStyle(.secondary)
          .frame(width: 28, alignment: .center)
      }

      ArtworkImage(
        artworkPath: song.effectiveArtworkPath,
        size: 40,
        cornerRadius: artworkShape == .circle ? 20 : 4
      )

      VStack(alignment: .leading, spacing: 2) {
        Text(song.title)
          .font(.system(size: 15, weight: isCurrent ? .semibold : .regular))
          .lineLimit(1)

        HStack(spacing: 4) {
          if song.isExplicit { ExplicitBadge(size: 11) }
          if song.isAIGenerated { AIGeneratedBadge(size: 11) }
          if song.isRemote && !song.remoteIsDownloaded {
            RemoteSongBadge(isDownloading: song.remoteDownloadRequested, size: 10)
          }
          Text(song.artist)
            .font(.system(size: 13))
            .foregroundStyle(.secondary)
            .lineLimit(1)
        }
      }

      Spacer()
    }
    .padding(.vertical, 4)
    .songContextMenu(song: song)
  }
}
